### ISSUE TITLE
upgrade jakarta.annotations to v2

### ISSUE THREAD

**Issue by xenoterracide** [unitsofmeasurement/si-units#90] opened 2023-09-06 19:08 UTC
I ran into a problem with being unable to compile my spring boot project when upgrading to v3 (of spring boot). It now locks jakarta.annotations 2 which doesn't use the java.annotations of v1. Please upgrade usages to v2 which will use the jakarta namespace (yes, this is dumb, thanks jakarta and java) here's my build scan https://scans.gradle.com/s/oq6jr247fxnm2/dependencies?focusedDependency=WzIsMSw3OTYsWzIsMSxbNzk2XV1d&focusedDependencyView=versions&toggled=W1syXSxbMiwwXSxbMiwxXV0

**Comment by keilw** [comment] 2023-09-06 21:13
This seems a duplicate of #85

**Closed by keilw** 2023-09-06 21:13 UTC
Labels: duplicate

**Comment by xenoterracide** [comment] 2023-09-06 21:18
Different symptom but the same fix will fix it.
